# Site settings
title: Steven's Web Thoughts
email: xksteven at gmail.com
description: "A researcher's journey through machine learning and computer science."
baseurl: ""
url: "http://stevenbas.art"
#twitter_username: jekyllrb
github_username:  xksteven

# Build settings
markdown: kramdown
permalink: pretty
