# Site settings
title: Steven's Web Thoughts
email: xksteven at uchicago.com
description: "A UChicago student's journey through machine learning and computer science."
baseurl: ""
# Used for testing
url: "localhost:4000"

#twitter_username: jekyllrb
github_username:  xksteven

# Build settings
markdown: kramdown
permalink: pretty
